environment:
    global:
      PYTHON: "C:\\Python36"

    matrix:
        # TODO: add "PIP: 20.0" after pip==20.1 being released

        - TOXENV: py27-piplatest-coverage
          PIP: latest

        - TOXENV: py35-piplatest
          PIP: latest

        - TOXENV: py36-piplatest
          PIP: latest

        - TOXENV: py37-piplatest
          PIP: latest

        - TOXENV: py38-piplatest-coverage
          PIP: latest

matrix:
  fast_finish: true
  allow_failures:
    - PIP: master

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - pip install tox

build: false

test_script:
    - tox

after_test:
  # Add tox environment to PATH.
  - "SET PATH=%CD%\\.tox\\%TOXENV%\\scripts;%PATH%"
  - IF NOT "x%TOXENV:-coverage=%"=="x%TOXENV%" (
      pip install codecov &&
      coverage xml &&
      appveyor-retry codecov --required -X gcov pycov search -f coverage.xml -n %TOXENV%-windows
    )
