environment:
    global:
      PYTHON: "C:\\Python36"

    matrix:
        - TOXENV: py27-pip20.0-coverage
          PIP: 20.0
        - TOXENV: py27-pipmaster-coverage
          PIP: master
        - TOXENV: py27-piplatest-coverage
          PIP: latest

        - TOXENV: py35-pip20.0-coverage
          PIP: 20.0
        - TOXENV: py35-pipmaster-coverage
          PIP: master
        - TOXENV: py35-piplatest-coverage
          PIP: latest

        - TOXENV: py36-pip20.0-coverage
          PIP: 20.0
        - TOXENV: py36-pipmaster-coverage
          PIP: master
        - TOXENV: py36-piplatest-coverage
          PIP: latest

        - TOXENV: py37-pip20.0-coverage
          PIP: 20.0
        - TOXENV: py37-pipmaster-coverage
          PIP: master
        - TOXENV: py37-piplatest-coverage
          PIP: latest

        - TOXENV: py38-pip20.0-coverage
          PIP: 20.0
        - TOXENV: py38-pipmaster-coverage
          PIP: master
        - TOXENV: py38-piplatest-coverage
          PIP: latest

matrix:
  fast_finish: true
  allow_failures:
    - PIP: master

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

    # Temporary workaround to prevent tests failing.
    # See GH-983 for the details.
    # TODO remove this after tox>3.14.0 being released
    - pip install "virtualenv>=16.0.0"

    - pip install tox

build: false

test_script:
    - tox

after_test:
  # Add tox environment to PATH.
  - "SET PATH=%CD%\\.tox\\%TOXENV%\\scripts;%PATH%"
  - IF NOT "x%TOXENV:-coverage=%"=="x%TOXENV%" (
      pip install codecov &&
      coverage xml &&
      appveyor-retry codecov --required -X gcov pycov search -f coverage.xml -n %TOXENV%-windows
    )
